"""
Forecast Explorer Page.
Displays forecast results generated by the best forecasting model.
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path
from plotly.graph_objs import Figure


@st.cache_data
def load_csv_data(file_path: Path) -> pd.DataFrame:
    """
    Loads data from a CSV file.
    
    Args:
        file_path (Path): The path to the CSV file.
        
    Returns:
        pd.DataFrame: The loaded DataFrame, or an empty DataFrame if file not found.
    """
    if file_path.exists():
        return pd.read_csv(file_path)
    return pd.DataFrame()


def create_forecast_bar_chart(df: pd.DataFrame, x_col: str, y_col: str, title: str) -> Figure:
    """
    Creates a responsive bar chart for forecast data.
    
    Args:
        df (pd.DataFrame): The data to plot.
        x_col (str): The column to use for the x-axis.
        y_col (str): The column to use for the y-axis.
        title (str): The chart title.
        
    Returns:
        Figure: The plotly Figure object.
    """
    fig = px.bar(
        df, 
        x=x_col, 
        y=y_col, 
        title=title, 
        text_auto='.2s', 
        color=x_col
    )
    return fig


def create_forecast_line_chart(df: pd.DataFrame, x_col: str, y_col: str, title: str) -> Figure:
    """
    Creates a responsive line chart for forecast data.
    
    Args:
        df (pd.DataFrame): The data to plot.
        x_col (str): The column to use for the x-axis.
        y_col (str): The column to use for the y-axis.
        title (str): The chart title.
        
    Returns:
        Figure: The plotly Figure object.
    """
    fig = px.line(
        df, 
        x=x_col, 
        y=y_col, 
        title=title, 
        markers=True
    )
    return fig


def display_model_metrics(metrics_df: pd.DataFrame) -> None:
    """
    Displays the model performance metrics dynamically from the metrics DataFrame.
    
    Args:
        metrics_df (pd.DataFrame): The DataFrame containing model metrics.
    """
    st.subheader("4. Model Performance Metrics")
    
    if metrics_df.empty:
        st.warning("Performance metrics are currently unavailable.")
        return
        
    # Assume the first row contains the best model's metrics
    best_model = metrics_df.iloc[0]
    
    st.markdown(f"**Best Model:** {best_model.get('Model', 'Unknown')}")
    
    cols = st.columns(3)
    with cols[0]:
        mae = best_model.get('MAE', 0)
        st.metric("MAE (Mean Absolute Error)", f"{mae:,.2f}")
        
    with cols[1]:
        rmse = best_model.get('RMSE', 0)
        st.metric("RMSE (Root Mean Squared Error)", f"{rmse:,.2f}")
        
    with cols[2]:
        mape = best_model.get('MAPE', 0)
        st.metric("MAPE (Mean Absolute Percentage Error)", f"{mape:,.2f}%")


def main() -> None:
    """
    Main function to render the Forecast Explorer page.
    """
    st.title("Forecast Explorer")
    st.write("Display forecast results generated by the best forecasting model.")
    
    # Use pathlib for robust path resolution
    base_dir = Path(__file__).resolve().parent.parent / "data" / "processed"
    forecast_summary_path = base_dir / "forecast_summary.csv"
    region_forecast_path = base_dir / "region_forecast_summary.csv"
    category_forecast_path = base_dir / "category_forecast_summary.csv"
    
    # Sidebar Controls
    st.sidebar.header("Forecast Settings")
    forecast_type = st.sidebar.selectbox("Forecast Type", ["Region", "Category"])
    
    # Forecast Horizon is a UI requirement
    _ = st.sidebar.selectbox("Forecast Horizon", ["1 Month", "2 Months", "3 Months"])
    
    # Load specific data based on type
    data_df = pd.DataFrame()
    x_column = ""
    y_column = "Forecast Next Month"
    
    if forecast_type == "Region":
        data_df = load_csv_data(region_forecast_path)
        x_column = "Region"
        if data_df.empty:
            st.warning("Region forecast data not available.")
    else:
        data_df = load_csv_data(category_forecast_path)
        x_column = "Category"
        if data_df.empty:
            st.warning("Category forecast data not available.")
            
    # Display the interactive content if data is available
    if not data_df.empty and x_column in data_df.columns:
        # Dynamic Dropdown for Selection based on Forecast Type
        options = data_df[x_column].unique().tolist()
        selected_options = st.sidebar.multiselect("Selection", options=options, default=options)
        
        filtered_df = data_df[data_df[x_column].isin(selected_options)]
        
        if filtered_df.empty:
            st.info(f"Please select at least one {x_column.lower()} to view the forecast.")
        else:
            # 1. Forecast Table
            st.subheader("1. Forecast Table")
            st.dataframe(filtered_df, use_container_width=True)
            
            # Layout for charts
            chart_col1, chart_col2 = st.columns(2)
            
            with chart_col1:
                # 2. Forecast Bar Chart
                st.subheader("2. Forecast Bar Chart")
                bar_chart = create_forecast_bar_chart(
                    filtered_df, 
                    x_col=x_column, 
                    y_col=y_column, 
                    title=f"Forecast by {forecast_type}"
                )
                st.plotly_chart(bar_chart, use_container_width=True)
                
            with chart_col2:
                # 3. Forecast Line Chart
                st.subheader("3. Forecast Line Chart")
                line_chart = create_forecast_line_chart(
                    filtered_df, 
                    x_col=x_column, 
                    y_col=y_column, 
                    title=f"Forecast by {forecast_type}"
                )
                st.plotly_chart(line_chart, use_container_width=True)
                
    st.divider()
    
    # 4. Model Performance Metrics
    metrics_df = load_csv_data(forecast_summary_path)
    display_model_metrics(metrics_df)


if __name__ == "__main__":
    main()
